### ISSUE TITLE
Feature Request: add a symbol to put value with open closing square brackets.

### ISSUE THREAD

**Issue by msarson** [mikeduglas/printf#1]
Hi Mike, 

When I use ODS, I often enclose a value in square brackets. A symbol for this would prove useful.

An example.

```ODS('LOC:ReturnValue = [' & LOC:ReturnValue & ']')```

Feel free to use or close :)

Regards

Mark

**Comment by mikeduglas** [comment]
Hi Mark,

Thanks for the feedback!
I think this use case is too special, also printf('[%s]', LOC:ReturnValue)
is more readable than for example printf('%[', LOC:ReturnValue).

--
Mike

**Comment by msarson** [comment]
Duh, sorry Mike, was just thinking out of the box, without thinking, long hot day here.

Of course your option is better.

Mark

**Comment by mikeduglas** [comment]
Closing for now, feel free to reopen if you have another suggestion.
